### ISSUE TITLE
Snackbar from Design Support library throws Null Pointer Exception after adding this library

### ISSUE THREAD

**Issue by r4hulp** [fabionuno/FloatingActionButton-Xamarin.Android#3]
Hi,

I wanted to implement Floating Action Menu in my existing app. I added this library along with Design support library.

I wanted to show snackbar on click of Floating Action Button. But I got this exception..

```
{Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2185/53fce373/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61 
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00064] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1301 
  at Android.Support.Design.Widget.Snackbar.Make (Android.Views.View view, ICharSequence text, Int32 duration) [0x00078] in <filename unknown>:0 
  at Android.Support.Design.Widget.Snackbar.Make (Android.Views.View view, System.String text, Int32 duration) [0x00013] in <filename unknown>:0 
  at Cheesesquare.CheeseDetailActivity.fabPhoto_Click (System.Object sender, System.EventArgs e) [0x00002] in d:\Puppy Projects\Cheesesquare\CheeseDetailActivity.cs:55 
  --- End of managed exception stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
    at android.support.design.widget.Snackbar.setText(Snackbar.java:331)
    at android.support.design.widget.Snackbar.make(Snackbar.java:207)
    at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
    at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:29)
    at android.view.View.performClick(View.java:4789)
    at android.view.View$PerformClick.run(View.java:19881)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5294)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
}
```

After removing this library, snackbar started working fine!

**Comment by fabionuno** [comment]
Hi Rahul.
I will try to do a sample project to reproduce this issue.
Can you provide more information about your project, like the Android target version and the Support Library version ?

**Comment by fabionuno** [comment]
This issue can be solved updating the Support Libraries to revision 23.0.1.
I added an example of the FloatingActionMenu with Snackbar and CoordinatorLayout.  I think this can help you.

**Comment by toSilence** [comment]
Hi,

I have the same exception with support library 23.0.1.3.

Maybe it is not working again?

Best Regards

**Comment by fabionuno** [comment]
Hi @toSilence can you provide more information about how to reproduce this issue?
This issue occurs in debug or release mode?

Last night I did a downgrade of support libraries used by the sample project to check this issue and i'm not able to reproduce this.
Can you try to do the same with the sample project?
